FROM       node:9.2.0						
RUN          mkdir -p /TodoMVCService					 
WORKDIR /TodoMVCService 					      		
COPY      . /TodoMVCService							
RUN          npm install 							
EXPOSE    3000							  	
CMD         npm start  						
